debezium/debezium-connector-db2

src/main/java/io/debezium/connector/db2/Db2ChangeTable.java, src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2ObjectNameQuoter.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/test/java/io/debezium/connector/db2/Db2CaseSensitiveObjectIT.java, src/test/java/io/debezium/connector/db2/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2796
CC @lga-zurich
=> DBZ-2796 Support for lowercase table and schema names in Db2

README.md
https://issues.redhat.com/browse/DBZ-2802
=> DBZ-2802 Update build status badge in README.md

.github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-3012
=> DBZ-3012 Ignore .md files upon CI build

.github/workflows/maven.yml
=> DBZ-3012 Fix Indentation

README.md, src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2424
=> DBZ-2424 Use database configs from RelationalDatabaseConnectorConfig as of DBZ-2420

src/main/java/io/debezium/connector/db2/Db2Connection.java
http://issues.redhat.com/browse/DBZ-3151
=> DBZ-3151 Filter table indices with no name

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java
https://issues.redhat.com/browse/DBZ-3271
Requires https://github.com/debezium/debezium/pull/2211/
=> DBZ-3271 Centralizing column filter handling

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
https://issues.redhat.com/browse/DBZ-2511
=> DBZ-2511 Dedicated logger for schema name adjuster

README.md, pom.xml
https://issues.redhat.com/browse/DBZ-3449
=> DBZ-3449 Adding 'quick' profile

.github/workflows/maven.yml, src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2Connector.java, src/test/java/io/debezium/connector/db2/Db2ConnectorTest.java
https://issues.redhat.com/browse/DBZ-3118
=> DBZ-3118 Config validation for Db2

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2OffsetContext.java, src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java
Depends on https://github.com/debezium/debezium/pull/2348
=> DBZ-3500 Incremental snapshots for Db2

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2OffsetContext.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, src/test/java/io/debezium/connector/db2/util/TestHelper.java
See [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975).
This PR complements https://github.com/debezium/debezium/pull/2283.
**TODO**:
=> DBZ-2975: Extract offset context from object states to method signatures

src/main/java/io/debezium/connector/db2/Db2ChangeRecordEmitter.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2OffsetContext.java, src/main/java/io/debezium/connector/db2/Db2Partition.java, src/main/java/io/debezium/connector/db2/Db2SchemaChangeEventEmitter.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java
See [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975).
This PR complements https://github.com/debezium/debezium/pull/2546.
**TODO**:
=> DBZ-2975: Remove partition from offset context

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-2525
=> DBZ-2525 Generifying exclusion of columns from snapshotting

src/test/java/io/debezium/connector/db2/Db2ConnectorConfigDefTest.java
closes https://issues.redhat.com/browse/DBZ-3943
=> DBZ-3943 add ConfigDef test to check for empty or unset `Field#description`

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java
Required for https://github.com/debezium/debezium/pull/2708
=> DBZ-4013 Guard against empty schema name

.github/workflows/cross-maven.yml, .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-4289
=> DBZ-4289 Avoiding superfluous component builds

src/main/java/io/debezium/connector/db2/Db2ChangeRecordEmitter.java
Refer https://issues.redhat.com/browse/DBZ-4351
=> DBZ-4351 Add create/update/delete event seen metrics for monitor upstream dml operation for db2 connector

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
Depends on https://github.com/debezium/debezium/pull/3143
=> DBZ-4577 Provide custom error message handling

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java
See [DBZ-4478](https://issues.redhat.com/browse/DBZ-4478).
This PR complements https://github.com/debezium/debezium/pull/2946.
=> DBZ-4478: Partition-scoped metrics for the SQL Server connector

src/main/java/io/debezium/connector/db2/Db2OffsetContext.java
https://github.com/debezium/debezium/pull/3519
Implements the changes of this PR in this connector and fixes the build.
It builds locally with the changes in the above PR included but will obviously fail standalone. Thank you!
=> DBZ-5136: OffsetContext changes to generify setting the snapshot marker

src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java
https://issues.redhat.com/browse/DBZ-4251
=> DBZ-4251 Add incremental snapshot tests

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java
https://issues.redhat.com/browse/DBZ-5045
=> DBZ-5045 Remove deprecated SCHEMA_WHITELIST and SCHEMA_BLACKLIST

src/main/java/io/debezium/connector/db2/Db2SchemaChangeEventEmitter.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-4451
=> DBZ-4451 Use SchemaChangeEvent factory methods

src/main/java/io/debezium/connector/db2/Db2SourceInfoStructMaker.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java
https://issues.redhat.com/browse/DBZ-4834
This is the sibling PR which can only be merged after https://github.com/debezium/debezium/pull/3600
=> DBZ-4834 Fix incremental snapshot of table added to include list

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2DatabaseSchema.java, src/main/java/io/debezium/connector/db2/Db2EventMetadataProvider.java, src/main/java/io/debezium/connector/db2/Db2OffsetContext.java
https://issues.redhat.com/browse/DBZ-4180
=> DBZ-4180 Pluggable topic selector

.github/workflows/cross-maven.yml, .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-5409
=> DBZ-5409 Build stable branches for Db2 on push/pull event

src/test/java/io/debezium/connector/db2/util/TestHelper.java, src/test/resources/logback-test.xml
No actual solution for [DBZ-5149](https://issues.redhat.com/browse/DBZ-5149). As I wasn't able to figure out where the problem could be, let's try to add some logging if it will give some hints where to look.
=> DBZ-5149 Add debug logging for checking CDC status

src/main/java/io/debezium/connector/db2/Db2TopicSelector.java
https://issues.redhat.com/browse/DBZ-5457
=> DBZ-5457 Deprecate legacy topic selector for all connectors

.github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-5492
=> DBZ-5492 Use github.ref instead of github.base_ref

src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java
Depends on https://github.com/debezium/debezium/pull/3834
=> DBZ-3293 Add signal table automatically to include list

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/test/java/io/debezium/connector/db2/Db2ConnectorTest.java, src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java, src/test/java/io/debezium/connector/db2/SourceInfoTest.java, src/test/java/io/debezium/connector/db2/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-5043
Changes related to https://github.com/debezium/debezium/pull/3804
=> DBZ-5043 Use topix.prefix instead of database.server.name

src/main/java/io/debezium/connector/db2/Db2SchemaFactory.java
https://issues.redhat.com/browse/DBZ-5044
=> DBZ-5044 Introduce SchemaFactory for Db2

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/test/java/io/debezium/connector/db2/SourceInfoTest.java, src/test/java/io/debezium/connector/db2/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-5043
=> DBZ-5043 Reflect move of TOPIC_PREFIX to CommonConnectorConfig

src/main/java/io/debezium/connector/db2/Db2Connection.java
Related https://github.com/debezium/debezium/pull/3855
https://issues.redhat.com/browse/DBZ-5591
=> DBZ-5591 Snapshot process setting source.ts_ms

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java
https://issues.redhat.com/browse/DBZ-5671
=> DBZ-5671 Remove logic name parameter from sub connector config

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2DatabaseSchema.java, src/main/java/io/debezium/connector/db2/Db2DefaultValueConverter.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, src/test/java/io/debezium/connector/db2/AbstractDb2DefaultValueIT.java, src/test/java/io/debezium/connector/db2/Db2OfflineDefaultValueIT.java, src/test/java/io/debezium/connector/db2/Db2OnlineDefaultValueIT.java, src/test/java/io/debezium/connector/db2/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-4990
https://issues.redhat.com/browse/DBZ-5670
=> DBZ-4990 DBZ-5670 Default value and Schema changes support

pom.xml, src/test/java/io/debezium/connector/db2/AbstractDb2DefaultValueIT.java, src/test/java/io/debezium/connector/db2/Db2CaseSensitiveObjectIT.java, src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java, src/test/java/io/debezium/connector/db2/Db2ConnectorTest.java, src/test/java/io/debezium/connector/db2/SchemaHistoryTopicIT.java, src/test/java/io/debezium/connector/db2/SourceInfoTest.java, src/test/java/io/debezium/connector/db2/TransactionMetadataIT.java
Counterpart to https://github.com/debezium/debezium/pull/4012
https://issues.redhat.com/browse/DBZ-5779
=> DBZ-5779 Migrated debezium-connector-db2 to AssertJ

pom.xml
https://issues.redhat.com/browse/DBZ-2131
=> DBZ-2131 Add Apicurion profile

pom.xml
https://issues.redhat.com/browse/DBZ-5838
=> DBZ-5838 Add missing Apicurio converter dependency

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/main/java/io/debezium/connector/db2/Db2ObjectNameQuoter.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, src/main/java/io/debezium/connector/db2/Lsn.java, src/test/java/io/debezium/connector/db2/AbstractDb2DefaultValueIT.java
Depends on https://github.com/debezium/debezium/pull/4183
=> DBZ-2439 DBZ-4669 Align with new formatter/checkstyle

.github/workflows/contributor-check.yml, .github/workflows/cross-maven.yml, .github/workflows/octocat-commits-check.yml, .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-5998
=> DBZ-5998 Use correct format for GITHUB_OUTPUT in CI

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2DatabaseSchema.java
https://issues.redhat.com/browse/DBZ-5743
=> DBZ-5743 Introduce a new unicode topic naming strategy

src/main/java/io/debezium/connector/db2/Db2SchemaChangeEventEmitter.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-6070
=> DBZ-6070 DDL events not stored in schema history topic for excluded tables

src/main/java/io/debezium/connector/db2/Db2Connection.java
https://issues.redhat.com/browse/DBZ-6388
=> DBZ-6388 __source_ts_ms r (read) operation date is set to future for SQL Server

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java
related to https://github.com/debezium/debezium/pull/4477
=> DBZ-4027: Make signalling channel configurable

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/test/java/io/debezium/connector/db2/NotificationsIT.java
https://issues.redhat.com/browse/DBZ-1973
follow https://github.com/debezium/debezium/pull/4515
=> DBZ-1973 Add support for Notifications

src/test/java/io/debezium/connector/db2/NotificationsIT.java
related to https://github.com/debezium/debezium/pull/4569
=> DBZ-6424 Align NotificationsIT tests

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java, src/test/java/io/debezium/connector/db2/NotificationsIT.java
refer to: https://github.com/debezium/debezium/pull/4614
=> DBZ-6416 Add Initial snapshot notifications

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
refers to: https://github.com/debezium/debezium/pull/4635#issuecomment-1604061052
=> DBZ-6417 Remove signal action registration from Db2ConnectorTask

src/main/java/io/debezium/connector/db2/Db2TaskContext.java
https://issues.redhat.com/browse/DBZ-6603
=> DBZ-6603 Support for custom tags in the connector metrics

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
Relates to https://github.com/debezium/debezium/pull/4678
=> DBZ-6670 Replace error handler instead of recreate in order to keep retry counter

src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, src/test/java/io/debezium/connector/db2/BlockingSnapshotIT.java
relates to: https://github.com/debezium/debezium/pull/4711
=> DBZ-6566 Support Blocking snapshot for Db2

src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, src/test/java/io/debezium/connector/db2/BlockingSnapshotIT.java
related to: https://github.com/debezium/debezium/pull/4741
=> DBZ-6731 Support blocking snapshot

src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-6828
related to: https://github.com/debezium/debezium/pull/4824
=> DBZ-6828 Ad-hoc blocking snaps trigger emits schema changes of all tables

src/main/java/io/debezium/connector/db2/converters/Db2CloudEventsProvider.java, src/main/java/io/debezium/connector/db2/converters/Db2RecordParser.java
=> DBZ-3642 Pass record and metadata when creating parser for CloudEvents conversion

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/test/java/io/debezium/connector/db2/Db2ReselectColumnsProcessorIT.java
https://issues.redhat.com/browse/DBZ-4321
Sibling to main repository PR https://github.com/debezium/debezium/pull/5081
=> DBZ-4321 Add `PostProcessor` support

src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/5138
=> DBZ-7311 Permits to execute a blocking snapshot even if snapshot.mode=never

src/main/java/io/debezium/connector/db2/Db2ChangeEventSourceFactory.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
Related to https://github.com/debezium/debezium/pull/5196
=> DBZ-7301 Inject the SnapshotterService

src/test/java/io/debezium/connector/db2/Db2ReselectColumnsProcessorIT.java
https://issues.redhat.com/browse/DBZ-7491
=> DBZ-7491 Always clean-up after each Db2ReselectColumnsProcessorIT test

src/test/java/io/debezium/connector/db2/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-7107
Requires - https://github.com/debezium/debezium/pull/5261
=> DBZ-7107 Add micro/nano second based timestamps to source info block

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
related to: https://github.com/debezium/debezium/pull/5436
=> DBZ-7717 LogPositionValidator is no more needed in Db2Connection

src/main/java/io/debezium/connector/db2/snapshot/lock/ExclusiveSnapshotLock.java, src/main/java/io/debezium/connector/db2/snapshot/lock/NoSnapshotLock.java, src/main/java/io/debezium/connector/db2/snapshot/query/SelectAllSnapshotQuery.java
related to: https://github.com/debezium/debezium/pull/5460
=> DBZ-7732 Add connector specific annotation to SnapshotLock and SnapshotQuery implementations

src/main/java/io/debezium/connector/db2/Db2Connection.java
related to: https://github.com/debezium/debezium/pull/5473
=> DBZ-7765 Add Partition parameter to validateLogPosition

src/test/java/io/debezium/connector/db2/NotificationsIT.java
related to: https://github.com/debezium/debezium/pull/5559
=> DBZ-7858 Align NotificationsIT test to core changes

src/main/java/io/debezium/connector/db2/Db2TaskContext.java
relates to: https://github.com/debezium/debezium/pull/5718
=> DBZ-8035 Align core changes

src/test/java/io/debezium/connector/db2/SourceInfoTest.java
Depends on https://github.com/debezium/debezium/pull/6037
=> DBZ-8499 Make source info versioned

src/main/java/io/debezium/connector/db2/Db2Connection.java, src/test/java/io/debezium/connector/db2/IncrementalSnapshotIT.java
closes: https://issues.redhat.com/browse/DBZ-8833
=> DBZ-8833 Fix Db2 quotedTableIdString

src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-9208
Aligns with core changes in https://github.com/debezium/debezium/pull/6554
=> DBZ-9208 Use new offsets for non-recovery snapshot modes

src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java
Refer to https://github.com/debezium/debezium/pull/6468 for additional details.
=> DBZ-8968: Add support for pluggable ArrayDeque
